version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - "**/*"
  name: mangesh
  discard-paths: no

#     - './android/app/build/outputs/**/*.apk'
#  discard-paths: yes
